apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production
  namespace: argo-cd
  finalizers: 
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Production Environment
  sourceRepos:
  - '*'
  destinations:
  - namespace: prod
    server: https://kubernetes.default.svc
  - namespace: argo-cd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'